const countries = [
    {
      imageSrc: 'AD.png',
      hint: 'West Europe',
      answer: 'andorra',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'AE.png',
      hint: 'Middle East',
      answer: 'united arab emirates',
      altAnswer: 'uae',
    },
    {
      imageSrc: 'AF.png',
      hint: 'Central Asia',
      answer: 'afghanistan',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'AG.png',
      hint: 'Caribbean',
      answer: 'antigua and barbuda',
      altAnswer: 'antigua',
    },
    { imageSrc: 'AL.png', hint: 'Balkans', answer: 'albania', altAnswer: 'N/A' },
    {
      imageSrc: 'AM.png',
      hint: 'Near East',
      answer: 'armenia',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'AO.png',
      hint: 'South Africa',
      answer: 'angola',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'AR.png',
      hint: 'South America',
      answer: 'argentina',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'AT.png',
      hint: 'West Europe',
      answer: 'austria',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'AU.png',
      hint: 'Oceania',
      answer: 'australia',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'AZ.png',
      hint: 'Near East',
      answer: 'azerbaijan',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'BA.png',
      hint: 'Balkans',
      answer: 'bosnia and herzagovina',
      altAnswer: 'bosnia',
    },
    {
      imageSrc: 'BB.png',
      hint: 'Caribbean',
      answer: 'barbados',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'BD.png',
      hint: 'Indian Subcontinent',
      answer: 'bangladesh',
      altAnswer: 'bengladesh',
    },
    {
      imageSrc: 'BE.png',
      hint: 'West Europe',
      answer: 'belgium',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'BF.png',
      hint: 'West Africa',
      answer: 'burkina faso',
      altAnswer: 'N/A',
    },
    { imageSrc: 'BG.png', hint: 'Balkans', answer: 'bulgaria', altAnswer: 'N/A' },
    {
      imageSrc: 'BH.png',
      hint: 'Middle East',
      answer: 'bahrain',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'BI.png',
      hint: 'East Africa',
      answer: 'burundi',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'BJ.png',
      hint: 'West Africa',
      answer: 'benin',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'BN.png',
      hint: 'South East Asia',
      answer: 'brunei',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'BO.png',
      hint: 'South America',
      answer: 'bolivia',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'BR.png',
      hint: 'South America',
      answer: 'brazil',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'BS.png',
      hint: 'Caribbean',
      answer: 'bahamas',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'BT.png',
      hint: 'Indian Subcontinent',
      answer: 'bhutan',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'BW.png',
      hint: 'South Africa',
      answer: 'botswana',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'BY.png',
      hint: 'East Europe',
      answer: 'belarus',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'BZ.png',
      hint: 'Central America',
      answer: 'belize',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'CA.png',
      hint: 'North America',
      answer: 'canada',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'CD.png',
      hint: 'Central Africa',
      answer: 'democratic republic of the congo',
      altAnswer: 'congo',
    },
    {
      imageSrc: 'CF.png',
      hint: 'Central Africa',
      answer: 'central african republic',
      altAnswer: 'car',
    },
    {
      imageSrc: 'CG.png',
      hint: 'Central Africa',
      answer: 'republic of the congo',
      altAnswer: 'congo',
    },
    {
      imageSrc: 'CH.png',
      hint: 'West Europe',
      answer: 'switzerland',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'CI.png',
      hint: 'West Africa',
      answer: 'ivory coast',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'CL.png',
      hint: 'South America',
      answer: 'chile',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'CM.png',
      hint: 'Central Africa',
      answer: 'cameroon',
      altAnswer: 'N/A',
    },
    { imageSrc: 'CN.png', hint: 'East Asia', answer: 'china', altAnswer: 'N/A' },
    {
      imageSrc: 'CO.png',
      hint: 'South America',
      answer: 'colombia',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'CR.png',
      hint: 'Central America',
      answer: 'costa rica',
      altAnswer: 'N/A',
    },
    { imageSrc: 'CU.png', hint: 'Caribbean', answer: 'cuba', altAnswer: 'N/A' },
    {
      imageSrc: 'CV.png',
      hint: 'West Africa',
      answer: 'cape verde',
      altAnswer: 'N/A',
    },
    { imageSrc: 'CY.png', hint: 'Near East', answer: 'cyprus', altAnswer: 'N/A' },
    {
      imageSrc: 'CZ.png',
      hint: 'East Europe',
      answer: 'czechia',
      altAnswer: 'czech republic',
    },
    {
      imageSrc: 'DE.png',
      hint: 'West Europe',
      answer: 'germany',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'DJ.png',
      hint: 'East Africa',
      answer: 'djibouti',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'DK.png',
      hint: 'West Europe',
      answer: 'denmark',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'DM.png',
      hint: 'Caribbean',
      answer: 'dominica',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'DO.png',
      hint: 'Caribbean',
      answer: 'dominican republic',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'DZ.png',
      hint: 'North Africa',
      answer: 'algeria',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'EC.png',
      hint: 'South America',
      answer: 'ecuador',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'EE.png',
      hint: 'East Europe',
      answer: 'estonia',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'EG.png',
      hint: 'North Africa',
      answer: 'egypt',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'ER.png',
      hint: 'East Africa',
      answer: 'eritrea',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'ES.png',
      hint: 'West Europe',
      answer: 'spain',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'ET.png',
      hint: 'East Africa',
      answer: 'ethiopia',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'FI.png',
      hint: 'East Europe',
      answer: 'finland',
      altAnswer: 'N/A',
    },
    { imageSrc: 'FJ.png', hint: 'Oceania', answer: 'fiji', altAnswer: 'N/A' },
    {
      imageSrc: 'FM.png',
      hint: 'Oceania',
      answer: 'micronesia',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'FR.png',
      hint: 'West Europe',
      answer: 'france',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'GA.png',
      hint: 'Central Africa',
      answer: 'gabon',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'GB.png',
      hint: 'West Europe',
      answer: 'united kingdom',
      altAnswer: 'uk',
    },
    {
      imageSrc: 'GD.png',
      hint: 'Caribbean',
      answer: 'grenada',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'GE.png',
      hint: 'Near East',
      answer: 'georgia',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'GH.png',
      hint: 'West Africa',
      answer: 'ghana',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'GM.png',
      hint: 'West Africa',
      answer: 'gambia',
      altAnswer: 'the gambia',
    },
    {
      imageSrc: 'GN.png',
      hint: 'West Africa',
      answer: 'guinea',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'GQ.png',
      hint: 'Central Africa',
      answer: 'equatorial guinea',
      altAnswer: 'N/A',
    },
    { imageSrc: 'GR.png', hint: 'Balkans', answer: 'greece', altAnswer: 'N/A' },
    {
      imageSrc: 'GT.png',
      hint: 'Central America',
      answer: 'guatemala',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'GW.png',
      hint: 'West Africa',
      answer: 'guinea bissau',
      altAnswer: 'guinea-bissau',
    },
    {
      imageSrc: 'GY.png',
      hint: 'South America',
      answer: 'guyana',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'HN.png',
      hint: 'Central America',
      answer: 'honduras',
      altAnswer: 'N/A',
    },
    { imageSrc: 'HR.png', hint: 'Balkans', answer: 'croatia', altAnswer: 'N/A' },
    { imageSrc: 'HT.png', hint: 'Caribbean', answer: 'haiti', altAnswer: 'N/A' },
    {
      imageSrc: 'HU.png',
      hint: 'East Europe',
      answer: 'hungary',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'ID.png',
      hint: 'South East Asia',
      answer: 'indonesia',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'IE.png',
      hint: 'West Europe',
      answer: 'ireland',
      altAnswer: 'N/A',
    },
    { imageSrc: 'IL.png', hint: 'Near East', answer: 'israel', altAnswer: 'N/A' },
    {
      imageSrc: 'IN.png',
      hint: 'Indian Subcontinent',
      answer: 'india',
      altAnswer: 'N/A',
    },
    { imageSrc: 'IQ.png', hint: 'Middle East', answer: 'iraq', altAnswer: 'N/A' },
    { imageSrc: 'IR.png', hint: 'Middle East', answer: 'iran', altAnswer: 'N/A' },
    {
      imageSrc: 'IS.png',
      hint: 'West Europe',
      answer: 'iceland',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'IT.png',
      hint: 'West Europe',
      answer: 'italy',
      altAnswer: 'N/A',
    },
    { imageSrc: 'JA.png', hint: 'East Asia', answer: 'japan', altAnswer: 'N/A' },
    {
      imageSrc: 'JM.png',
      hint: 'Caribbean',
      answer: 'jamaica',
      altAnswer: 'N/A',
    },
    { imageSrc: 'JO.png', hint: 'Near East', answer: 'jordan', altAnswer: 'N/A' },
    {
      imageSrc: 'KE.png',
      hint: 'East Africa',
      answer: 'kenya',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'KG.png',
      hint: 'Central Asia',
      answer: 'kyrgyzstan',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'KH.png',
      hint: 'South East Asia',
      answer: 'cambodia',
      altAnswer: 'N/A',
    },
    { imageSrc: 'KI.png', hint: 'Oceania', answer: 'kiribati', altAnswer: 'N/A' },
    {
      imageSrc: 'KM.png',
      hint: 'East Africa',
      answer: 'comoros',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'KN.png',
      hint: 'Caribbean',
      answer: 'saint kitts and nevis',
      altAnswer: 'st kitts and nevis',
    },
    { imageSrc: 'KO.png', hint: 'Balkans', answer: 'kosovo', altAnswer: 'N/A' },
    {
      imageSrc: 'KP.png',
      hint: 'East Asia',
      answer: 'north korea',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'KR.png',
      hint: 'East Asia',
      answer: 'south korea',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'KW.png',
      hint: 'Middle East',
      answer: 'kuwait',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'KZ.png',
      hint: 'Central Asia',
      answer: 'kazakhstan',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'LA.png',
      hint: 'South East Asia',
      answer: 'laos',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'LB.png',
      hint: 'Near East',
      answer: 'lebanon',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'LC.png',
      hint: 'Caribbean',
      answer: 'saint lucia',
      altAnswer: 'st lucia',
    },
    {
      imageSrc: 'LI.png',
      hint: 'West Europe',
      answer: 'liechtenstein',
      altAnswer: 'lichtenstein',
    },
    {
      imageSrc: 'LK.png',
      hint: 'Indian Subcontinent',
      answer: 'sri lanka',
      altAnswer: 'srilanka',
    },
    {
      imageSrc: 'LR.png',
      hint: 'West Africa',
      answer: 'liberia',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'LS.png',
      hint: 'South Africa',
      answer: 'lesotho',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'LT.png',
      hint: 'East Europe',
      answer: 'lithuania',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'LU.png',
      hint: 'West Europe',
      answer: 'luxembourg',
      altAnswer: 'luxemburg',
    },
    {
      imageSrc: 'LV.png',
      hint: 'East Europe',
      answer: 'latvia',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'LY.png',
      hint: 'North Africa',
      answer: 'libya',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'MA.png',
      hint: 'North Africa',
      answer: 'morocco',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'MC.png',
      hint: 'West Europe',
      answer: 'monaco',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'MD.png',
      hint: 'East Europe',
      answer: 'moldova',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'ME.png',
      hint: 'Balkans',
      answer: 'montenegro',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'MG.png',
      hint: 'East Africa',
      answer: 'madagascar',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'MH.png',
      hint: 'Oceania',
      answer: 'marshall islands',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'MK.png',
      hint: 'Balkans',
      answer: 'macedonia',
      altAnswer: 'N/A',
    },
    { imageSrc: 'ML.png', hint: 'West Africa', answer: 'mali', altAnswer: 'N/A' },
    {
      imageSrc: 'MM.png',
      hint: 'South East Asia',
      answer: 'myanmar',
      altAnswer: 'burma',
    },
    {
      imageSrc: 'MN.png',
      hint: 'East Asia',
      answer: 'mongolia',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'MR.png',
      hint: 'West Africa',
      answer: 'mauritania',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'MT.png',
      hint: 'West Europe',
      answer: 'malta',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'MU.png',
      hint: 'East Africa',
      answer: 'mauritius',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'MV.png',
      hint: 'Indian Subcontinent',
      answer: 'maldives',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'MW.png',
      hint: 'South Africa',
      answer: 'malawi',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'MX.png',
      hint: 'North America',
      answer: 'mexico',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'MY.png',
      hint: 'South East Asia',
      answer: 'malaysia',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'MZ.png',
      hint: 'South Africa',
      answer: 'mozambique',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'NA.png',
      hint: 'South Africa',
      answer: 'namibia',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'NE.png',
      hint: 'West Africa',
      answer: 'niger',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'NG.png',
      hint: 'West Africa',
      answer: 'nigeria',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'NI.png',
      hint: 'Central America',
      answer: 'nicaragua',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'NL.png',
      hint: 'West Europe',
      answer: 'netherlands',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'NO.png',
      hint: 'West Europe',
      answer: 'norway',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'NP.png',
      hint: 'Indian Subcontinent',
      answer: 'nepal',
      altAnswer: 'N/A',
    },
    { imageSrc: 'NR.png', hint: 'Oceania', answer: 'nauru', altAnswer: 'N/A' },
    {
      imageSrc: 'NZ.png',
      hint: 'Oceania',
      answer: 'new zealand',
      altAnswer: 'N/A',
    },
    { imageSrc: 'OM.png', hint: 'Middle East', answer: 'oman', altAnswer: 'N/A' },
    {
      imageSrc: 'PA.png',
      hint: 'Central America',
      answer: 'panama',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'PE.png',
      hint: 'South America',
      answer: 'peru',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'PG.png',
      hint: 'Oceania',
      answer: 'papua new guinea',
      altAnswer: 'papua',
    },
    {
      imageSrc: 'PH.png',
      hint: 'South East Asia',
      answer: 'philippines',
      altAnswer: 'phillipines',
    },
    {
      imageSrc: 'PK.png',
      hint: 'Indian Subcontinent',
      answer: 'pakistan',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'PL.png',
      hint: 'East Europe',
      answer: 'poland',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'PT.png',
      hint: 'West Europe',
      answer: 'portugal',
      altAnswer: 'N/A',
    },
    { imageSrc: 'PW.png', hint: 'Oceania', answer: 'palau', altAnswer: 'N/A' },
    {
      imageSrc: 'PY.png',
      hint: 'South America',
      answer: 'paraguay',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'QA.png',
      hint: 'Middle East',
      answer: 'qatar',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'RO.png',
      hint: 'East Europe',
      answer: 'romania',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'RS.png',
      hint: 'East Europe',
      answer: 'serbia',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'RU.png',
      hint: 'East Europe',
      answer: 'russia',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'RW.png',
      hint: 'East Africa',
      answer: 'rwanda',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'SA.png',
      hint: 'Middle East',
      answer: 'saudi arabia',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'SB.png',
      hint: 'Oceania',
      answer: 'solomon islands',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'SC.png',
      hint: 'East Africa',
      answer: 'seychelles',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'SD.png',
      hint: 'East Africa',
      answer: 'sudan',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'SE.png',
      hint: 'West Europe',
      answer: 'sweden',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'SG.png',
      hint: 'South East Asia',
      answer: 'singapore',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'SI.png',
      hint: 'East Europe',
      answer: 'slovenia',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'SK.png',
      hint: 'East Europe',
      answer: 'slovakia',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'SL.png',
      hint: 'West Africa',
      answer: 'sierra leone',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'SM.png',
      hint: 'West Europe',
      answer: 'san marino',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'SN.png',
      hint: 'West Africa',
      answer: 'senegal',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'SO.png',
      hint: 'East Africa',
      answer: 'somalia',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'SR.png',
      hint: 'South America',
      answer: 'suriname',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'SS.png',
      hint: 'East Africa',
      answer: 'south sudan',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'ST.png',
      hint: 'Central Africa',
      answer: 'sao tome and principe',
      altAnswer: 'sao tome',
    },
    {
      imageSrc: 'SV.png',
      hint: 'Central America',
      answer: 'el salvador',
      altAnswer: 'salvador',
    },
    { imageSrc: 'SY.png', hint: 'Near East', answer: 'syria', altAnswer: 'N/A' },
    {
      imageSrc: 'SZ.png',
      hint: 'South Africa',
      answer: 'swaziland',
      altAnswer: 'eswatini',
    },
    {
      imageSrc: 'TD.png',
      hint: 'Central Africa',
      answer: 'chad',
      altAnswer: 'tchad',
    },
    { imageSrc: 'TG.png', hint: 'West Africa', answer: 'togo', altAnswer: 'N/A' },
    {
      imageSrc: 'TH.png',
      hint: 'South East Asia',
      answer: 'thailand',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'TJ.png',
      hint: 'Central Asia',
      answer: 'tajikistan',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'TL.png',
      hint: 'South East Asia',
      answer: 'timor-leste',
      altAnswer: 'timor leste',
    },
    {
      imageSrc: 'TM.png',
      hint: 'Central Asia',
      answer: 'turkmenistan',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'TN.png',
      hint: 'North Africa',
      answer: 'tunisia',
      altAnswer: 'N/A',
    },
    { imageSrc: 'TO.png', hint: 'Oceania', answer: 'tonga', altAnswer: 'N/A' },
    { imageSrc: 'TR.png', hint: 'Near East', answer: 'turkey', altAnswer: 'N/A' },
    {
      imageSrc: 'TT.png',
      hint: 'Caribbean',
      answer: 'trinidad and tobago',
      altAnswer: 'trinidad',
    },
    { imageSrc: 'TV.png', hint: 'Oceania', answer: 'tuvalu', altAnswer: 'N/A' },
    { imageSrc: 'TW.png', hint: 'East Asia', answer: 'taiwan', altAnswer: 'N/A' },
    {
      imageSrc: 'TZ.png',
      hint: 'East Africa',
      answer: 'tanzania',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'UA.png',
      hint: 'East Europe',
      answer: 'ukraine',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'UG.png',
      hint: 'East Africa',
      answer: 'uganda',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'US.png',
      hint: 'North America',
      answer: 'united states of america',
      altAnswer: 'america',
    },
    {
      imageSrc: 'UY.png',
      hint: 'South America',
      answer: 'uruguay',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'UZ.png',
      hint: 'Central Asia',
      answer: 'uzbekistan',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'VA.png',
      hint: 'West Europe',
      answer: 'vatican city',
      altAnswer: 'vatican',
    },
    {
      imageSrc: 'VC.png',
      hint: 'Caribbean',
      answer: 'saint vincent and the grenedines',
      altAnswer: 'st vincent and the grenedines',
    },
    {
      imageSrc: 'VE.png',
      hint: 'South America',
      answer: 'venezuela',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'VN.png',
      hint: 'South East Asia',
      answer: 'vietnam',
      altAnswer: 'viet nam',
    },
    { imageSrc: 'VU.png', hint: 'Oceania', answer: 'vanuatu', altAnswer: 'N/A' },
    { imageSrc: 'WS.png', hint: 'Oceania', answer: 'samoa', altAnswer: 'N/A' },
    {
      imageSrc: 'YE.png',
      hint: 'Middle East',
      answer: 'yemen',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'ZA.png',
      hint: 'South Africa',
      answer: 'south africa',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'ZM.png',
      hint: 'South Africa',
      answer: 'zambia',
      altAnswer: 'N/A',
    },
    {
      imageSrc: 'ZW.png',
      hint: 'South Africa',
      answer: 'zimbabwe',
      altAnswer: 'N/A',
    },
  ];
  
  export default countries;